import type { Metadata } from "next";
import { Lato } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next";

import "./globals.css";

import { ConvexClientProvider } from "@/components/providers/ConvexClientProvider";
import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";
import Modals from "@/components/modals";
import { Toaster } from "@/components/ui/sonner";
import JotaiProvider from "@/components/providers/JotaiProvider";
import { PresentationSceneProvider } from "@/context/PresentationSceneContext";
import { PrototypeModeProvider } from "@/context/PrototypeModeContext";
import { ArcNavigationProvider } from "@/context/ArcNavigationContext";
import { GlobalNavigationHeader } from "@/components/presentation/GlobalNavigationHeader";

const lato = Lato({
  subsets: ["latin"],
  weight: ["400", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const convexUrl = process.env.NEXT_PUBLIC_CONVEX_URL;
const hasConvex = !!convexUrl && !convexUrl.includes("demo-disabled");

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const content = (
    <ConvexClientProvider>
      <JotaiProvider>
        <PresentationSceneProvider>
          <PrototypeModeProvider>
            <ArcNavigationProvider>
              <Toaster />
              {hasConvex && <Modals />}
              {/* Global Navigation Header - rendered once at root level */}
              <GlobalNavigationHeader />
              <NuqsAdapter>{children}</NuqsAdapter>
            </ArcNavigationProvider>
          </PrototypeModeProvider>
        </PresentationSceneProvider>
      </JotaiProvider>
    </ConvexClientProvider>
  );

  return (
    <html lang="en">
      <head>
        <link href="https://fonts.cdnfonts.com/css/itc-avant-garde-gothic" rel="stylesheet" />
      </head>
      <body className={lato.className}>
        {hasConvex ? (
          <ConvexAuthNextjsServerProvider>{content}</ConvexAuthNextjsServerProvider>
        ) : (
          content
        )}
      </body>
    </html>
  );
}
